### ISSUE TITLE
Gradient lights don't work

### ISSUE THREAD

**Issue by FEFELAND** [Aeroluna/Technicolor#10]
Game version: 1.18.0
Mod version: 1.0.6

Issue: Selecting "Gradient" under "Technicolor Lights" in the "Styles" menu makes no change to the lights. 
![image](https://user-images.githubusercontent.com/57236015/136239429-411f5e2a-e031-48b3-9c4c-1f7e7e244b0b.png)

**Comment by AndrewTheWolfdog** [comment]
I have the same issue too.

**Comment by Aeroluna** [comment]
This was an issue with Chroma, it should be fixed now.
