### ISSUE TITLE
Mod break chain notes

### ISSUE THREAD

**Issue by tschmidt05** [Aeroluna/Technicolor#12]
I went through downloading mods 1 at a time to figure out which one was causing a bug which the 'mini notes' in the chain notes were not able to be hit. Technicolor was the one which the bug occurred on

Video of the bug [here](https://youtu.be/cPOChNK63Uk)

**Comment by Aeroluna** [comment]
Fixed https://github.com/Aeroluna/Heck/commit/813628ff7e981ea2ef6b21f5da9ce096ca98e3ff
