### ISSUE TITLE
Lighting Effects not Working

### ISSUE THREAD

**Issue by WubzyGD** [Aeroluna/Technicolor#15]
I'm on Beat Saber 1.21. A pretty new player to the game, and I modded it pretty quickly. Used Mod Assistant to install technicolor, and it was beyond amazing, easily my favorite mod (thanks btw), but at some point, the mod just stopped working. Gradient walls work (I think), and there seems to be a gradient sort of bloom going beneath me, but I don't know what I updated or changed to make it stop working.

I tried uninstalling any mod that was not core except for technicolor, and it produced the same result: when I play a level, I'm left with a bright room with the default colors and no lighting effects whatsoever. I can't find the setting for static lights, and I cannot for the life of me find anything else that would have caused it. 

[This is what I see](https://youtu.be/zu5dbyySVEQ)

**Comment by Aeroluna** [comment]
Please include a log file for when this occurs

**Comment by WubzyGD** [comment]
[2022.06.12.21.38.05.log](https://github.com/Aeroluna/Technicolor/files/8890297/2022.06.12.21.38.05.log)

Attached is my latest available log. If you need more logs or more information I'll be available. Thanks for the help!

**Comment by Aeroluna** [comment]
Sorry but the current version of Chroma (v2.5.16), which Technicolor relies on, is incompatible with Beat Saber v1.21, you'll have to update your game to v1.22
