### ISSUE TITLE
1.37 PC BeatTogether multiplayer just not loading with Technicolor installed 

### ISSUE THREAD

**Issue by LiiilsGIT** [Aeroluna/Technicolor#21]
Testing the patreon build of 1.37 BeatTogether with a PC friend and he basically could not play any maps with this mod installed. We would get past the ready up screen and then trying to load into the map he would just be on a permanent black screen with no audio at all and then would instantly die when the map started. Attaching a log below where we replicated the issue twice 
[2024.07.19.00.32.01.log](https://github.com/user-attachments/files/16311671/2024.07.19.00.32.01.log)

**Comment by IvanVZabrodin** [comment]
Also experiencing the exact same issue, except for the fact that I am not using BeatTogether, just regular Beat Saber. Has anyone found a fix for this yet?

**Comment by Aeroluna** [comment]
fixed https://github.com/Aeroluna/Heck/commit/be2fe1256b3aea82b6e5c5b3422ddb9f85334524
