### ISSUE TITLE
Technicolor wont make walls and lights in custom maps rainbow like it did in an older version.

### ISSUE THREAD

**Issue by XenoJiiva0053** [Aeroluna/Technicolor#4]
![20210418030323_1](https://user-images.githubusercontent.com/79415823/115130932-151d2400-9ff4-11eb-983a-2352370c21cc.jpg)
![20210418030351_1](https://user-images.githubusercontent.com/79415823/115130933-177f7e00-9ff4-11eb-8008-d6566a62f62c.jpg)
Ive tried several setting and other stuff cant get it to be rainbow like it was in an older version. what do i need to do to getit like that again?

**Comment by Aeroluna** [comment]
Please provide more information such as the map and your log file.

**Comment by XenoJiiva0053** [comment]
The map is Helltaker by core pee and i can not find a log file from technicolor
[_latest.log](https://github.com/Aeroluna/Technicolor/files/6334604/_latest.log)

**Comment by Aeroluna** [comment]
Technicolor does not work on maps that use Chroma, such as the map you mentioned

**Comment by XenoJiiva0053** [comment]
thats interesting as it did work on them in an older version.
