### ISSUE TITLE
[Enhancement] A setting to allow technicolor to overide/work on chroma maps

### ISSUE THREAD

**Issue by XenoJiiva0053** [Aeroluna/Technicolor#5]
A setting that allows technicolor to work on chroma maps.

**Comment by CyanSnow** [comment]
no

**Comment by nttfiles** [comment]
no

**Comment by PlusOneRabbit** [comment]
no

**Comment by Nchi** [comment]
But this works already? Chroma has (had with 1.16 being out) an option for itself and it worked on the maps I tried forget atm which map tho

**Comment by Aeroluna** [comment]
As Nchi has stated, Chroma has an option to disable itself. This will allow you to use Technicolor on maps where Chroma is only a suggestion.
